In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import date, datetime, timedelta
from sklearn import linear_model

C:\Users\marie\AppData\Local\Temp\ipykernel_13020\3028730387.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
dirpath = os.getcwd()
data_path = os.path.join(dirpath, "..", "..", "delpro_vms", "data")
feature_path = os.path.join(dirpath, "data")
out_dir = "data"
# read vistit data
data_df = pd.read_csv(os.path.join(data_path, "merged_lactation.csv"))
# read features
feature_df = pd.read_csv(os.path.join(feature_path, "gmfeature_table.csv"))
feature_df = feature_df.rename(columns = lambda col: "_".join(col.split("_")[::-1]) if "_" in col else col)

In [4]:
data_df

,animal_number,min_date,max_date,count_date,min_dim,max_dim,lactation,milk_flow_duration_mean,yield_visit_mean,yield_lf_visit_mean,...,kickoff_rf_perc,kickoff_rr_perc,kickoff_front_perc,kickoff_back_perc,kickoff_any_perc,yield_lf_visit_sum,yield_lr_visit_sum,yield_rr_visit_sum,yield_rf_visit_sum,interval_visit_mean
0,454,2023-03-21,2023-11-17,246,0.0,241.0,7,381.243711,18.092107,3.775346,...,0.460829,2.764977,1.228879,7.834101,8.141321,2432.15,3276.69,3782.15,2131.24,31594.316436
1,571,2023-10-20,2023-11-17,29,0.0,28.0,6,450.400000,17.547333,3.515167,...,7.812500,20.312500,10.937500,32.812500,35.937500,225.47,392.54,309.63,175.25,37965.250000
2,627,2023-08-17,2023-11-17,94,0.0,92.0,6,244.504032,19.376452,3.784556,...,0.000000,0.000000,0.000000,0.000000,0.000000,948.77,1347.54,1480.53,1065.06,31442.340000
3,628,2023-10-17,2023-11-17,32,0.0,31.0,6,332.936709,16.635190,4.160886,...,0.000000,1.265823,0.000000,1.265823,1.265823,328.71,504.50,480.97,0.00,33534.810127
4,686,2023-09-28,2024-09-23,365,0.0,361.0,5,316.455366,20.467924,4.461334,...,0.098425,0.590551,0.196850,1.476378,1.574803,4501.31,5808.03,5664.09,4713.77,30266.279528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,1501,2023-10-27,2023-11-17,22,0.0,21.0,1,263.775000,13.026500,3.134250,...,30.232558,51.162791,44.186047,62.790698,62.790698,134.60,146.79,132.51,142.79,41876.093023
235,1503,2023-11-10,2024-10-22,354,0.0,347.0,1,319.529412,16.081324,3.855027,...,0.658762,0.527009,1.712780,1.054018,1.712780,2903.74,3052.96,3131.90,3077.57,39046.085639
236,1504,2023-11-06,2024-08-20,292,1.0,289.0,1,425.970423,13.171338,2.779789,...,0.273973,0.410959,0.410959,0.547945,0.821918,1993.32,2526.68,2512.82,2507.76,33584.263014
237,1507,2023-11-10,2023-11-17,8,0.0,7.0,1,318.642857,5.433571,0.634286,...,0.000000,0.000000,0.000000,13.333333,13.333333,9.17,1.03,35.07,32.75,40166.733333
238,1511,2023-11-14,2023-11-17,4,0.0,3.0,1,249.428571,6.834286,1.748571,...,28.571429,14.285714,28.571429,14.285714,28.571429,12.24,11.94,10.40,13.26,36587.428571

In [5]:
merged_long = pd.merge(feature_df, data_df, left_on = ["cow"], right_on = ["animal_number"])
merged_long.to_csv(os.path.join(out_dir, "lactation_features.csv"), index = False)

In [6]:
merged_long

,cow,vol_udder,vol_lf,vol_rf,vol_lb,vol_rb,sarea_udder,sarea_lf,sarea_rf,sarea_lb,...,kickoff_rf_perc,kickoff_rr_perc,kickoff_front_perc,kickoff_back_perc,kickoff_any_perc,yield_lf_visit_sum,yield_lr_visit_sum,yield_rr_visit_sum,yield_rf_visit_sum,interval_visit_mean
0,962,NaN,5.573958,4.085820,1.111412,1.092560,NaN,NaN,804.570532,NaN,...,0.307692,0.205128,1.948718,0.410256,0.717949,3175.66,5307.60,4774.74,2488.16,30466.209231
1,1023,5.714783,1.621162,1.699928,1.039928,0.918518,1950.088219,590.241475,618.252160,416.517287,...,0.000000,0.289017,0.000000,0.289017,0.289017,1666.72,1636.48,1743.94,1702.22,28775.031792
2,1061,8.568868,3.397686,3.202858,0.727902,NaN,2408.863832,851.636223,834.217005,294.634555,...,0.000000,0.125628,0.125628,0.125628,0.125628,4306.97,0.00,5646.94,4696.32,30406.453518
3,1074,8.226312,3.949914,1.996374,1.375643,0.793432,2117.660702,1062.524430,NaN,461.610765,...,0.174825,0.349650,0.262238,0.524476,0.611888,3802.15,5968.17,6219.16,3327.16,27177.992133
4,1081,9.478595,4.800454,3.181683,0.829021,0.593365,2463.079844,787.625015,783.390159,551.826780,...,0.000000,0.000000,0.000000,0.000000,0.000000,4266.76,4794.01,4617.52,4485.43,34578.254630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1486,5.378144,1.734115,1.861548,0.768159,0.702433,1964.898450,521.314016,589.685346,475.684154,...,1.754386,1.754386,1.754386,3.508772,4.093567,457.27,488.74,430.47,460.56,31781.508772
89,1487,8.376260,5.059448,3.538225,0.712471,0.503287,1788.671257,869.119892,720.359164,208.901041,...,0.000000,0.508906,0.890585,0.636132,0.636132,2633.47,3487.49,3339.83,2627.71,32828.129771
90,1495,5.783034,1.668636,3.162655,0.557299,0.537761,1910.238056,434.406296,775.294209,346.581440,...,2.173913,4.347826,2.173913,4.347826,4.347826,125.65,111.28,113.77,134.00,39553.326087
91,1501,7.486284,2.142604,4.278479,0.523835,0.720675,1688.992494,433.107657,923.958614,210.824871,...,30.232558,51.162791,44.186047,62.790698,62.790698,134.60,146.79,132.51,142.79,41876.093023
92,1504,5.590657,1.046042,2.229637,0.923492,NaN,2040.123938,385.794117,606.989457,438.238827,...,0.273973,0.410959,0.410959,0.547945,0.821918,1993.32,2526.68,2512.82,2507.76,33584.263014

In [7]:
feature_df

,cow,vol_udder,vol_lf,vol_rf,vol_lb,vol_rb,sarea_udder,sarea_lf,sarea_rf,sarea_lb,...,circ_lb,exc_lb,peri_rb,area_rb,circ_rb,exc_rb,len_lf,len_rf,len_lb,len_rb
0,962,NaN,5.573958,4.085820,1.111412,1.092560,NaN,NaN,804.570532,NaN,...,0.664384,NaN,505.274170,12677.0,0.623582,0.722236,42.457332,NaN,37.862155,NaN
1,1023,5.714783,1.621162,1.699928,1.039928,0.918518,1950.088219,590.241475,618.252160,416.517287,...,0.704307,0.662930,505.469083,13280.0,0.654886,0.577382,48.387121,44.500495,36.844776,37.681548
2,1061,8.568868,3.397686,3.202858,0.727902,NaN,2408.863832,851.636223,834.217005,294.634555,...,0.595592,0.578675,NaN,NaN,NaN,NaN,38.257350,49.539739,25.443040,NaN
3,1074,8.226312,3.949914,1.996374,1.375643,0.793432,2117.660702,1062.524430,NaN,461.610765,...,0.655057,0.548849,489.847763,10742.0,0.565089,0.856098,44.536724,NaN,NaN,NaN
4,1081,9.478595,4.800454,3.181683,0.829021,0.593365,2463.079844,787.625015,783.390159,551.826780,...,0.765194,0.434932,431.741161,10606.0,0.718633,0.682271,NaN,50.101244,45.335739,40.272096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,1486,5.378144,1.734115,1.861548,0.768159,0.702433,1964.898450,521.314016,589.685346,475.684154,...,NaN,0.785654,496.498521,11302.0,0.572537,0.778834,37.961439,37.554606,27.339605,23.264238
89,1487,8.376260,5.059448,3.538225,0.712471,0.503287,1788.671257,869.119892,720.359164,208.901041,...,0.676632,0.791993,354.205627,5754.5,0.602927,0.738296,42.302186,51.276823,26.069107,NaN
90,1495,5.783034,1.668636,3.162655,0.557299,0.537761,1910.238056,434.406296,775.294209,346.581440,...,NaN,0.727476,514.640656,10016.5,NaN,0.689949,31.150010,44.635441,27.101730,29.439392
91,1501,7.486284,2.142604,4.278479,0.523835,0.720675,1688.992494,433.107657,923.958614,210.824871,...,0.695512,0.658773,292.710678,5358.0,NaN,0.620216,47.620275,43.362852,37.554216,35.086378
92,1504,5.590657,1.046042,2.229637,0.923492,NaN,2040.123938,385.794117,606.989457,438.238827,...,0.572817,0.860755,522.877200,14700.0,0.673209,0.776201,NaN,51.345718,41.050008,NaN

In [8]:
data_df

,animal_number,min_date,max_date,count_date,min_dim,max_dim,lactation,milk_flow_duration_mean,yield_visit_mean,yield_lf_visit_mean,...,kickoff_rf_perc,kickoff_rr_perc,kickoff_front_perc,kickoff_back_perc,kickoff_any_perc,yield_lf_visit_sum,yield_lr_visit_sum,yield_rr_visit_sum,yield_rf_visit_sum,interval_visit_mean
0,454,2023-03-21,2023-11-17,246,0.0,241.0,7,381.243711,18.092107,3.775346,...,0.460829,2.764977,1.228879,7.834101,8.141321,2432.15,3276.69,3782.15,2131.24,31594.316436
1,571,2023-10-20,2023-11-17,29,0.0,28.0,6,450.400000,17.547333,3.515167,...,7.812500,20.312500,10.937500,32.812500,35.937500,225.47,392.54,309.63,175.25,37965.250000
2,627,2023-08-17,2023-11-17,94,0.0,92.0,6,244.504032,19.376452,3.784556,...,0.000000,0.000000,0.000000,0.000000,0.000000,948.77,1347.54,1480.53,1065.06,31442.340000
3,628,2023-10-17,2023-11-17,32,0.0,31.0,6,332.936709,16.635190,4.160886,...,0.000000,1.265823,0.000000,1.265823,1.265823,328.71,504.50,480.97,0.00,33534.810127
4,686,2023-09-28,2024-09-23,365,0.0,361.0,5,316.455366,20.467924,4.461334,...,0.098425,0.590551,0.196850,1.476378,1.574803,4501.31,5808.03,5664.09,4713.77,30266.279528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,1501,2023-10-27,2023-11-17,22,0.0,21.0,1,263.775000,13.026500,3.134250,...,30.232558,51.162791,44.186047,62.790698,62.790698,134.60,146.79,132.51,142.79,41876.093023
235,1503,2023-11-10,2024-10-22,354,0.0,347.0,1,319.529412,16.081324,3.855027,...,0.658762,0.527009,1.712780,1.054018,1.712780,2903.74,3052.96,3131.90,3077.57,39046.085639
236,1504,2023-11-06,2024-08-20,292,1.0,289.0,1,425.970423,13.171338,2.779789,...,0.273973,0.410959,0.410959,0.547945,0.821918,1993.32,2526.68,2512.82,2507.76,33584.263014
237,1507,2023-11-10,2023-11-17,8,0.0,7.0,1,318.642857,5.433571,0.634286,...,0.000000,0.000000,0.000000,13.333333,13.333333,9.17,1.03,35.07,32.75,40166.733333
238,1511,2023-11-14,2023-11-17,4,0.0,3.0,1,249.428571,6.834286,1.748571,...,28.571429,14.285714,28.571429,14.285714,28.571429,12.24,11.94,10.40,13.26,36587.428571