In [17]:
import os
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams.update({'font.size': 16})
import re

In [4]:
dirpath = os.getcwd()
features_path = r"C:\Users\marie\rep_codes\udder_project\udder_processing\features_dict\gmfeature_table.csv"
data_path = r"C:\Users\marie\rep_codes\udder_project\delpro_vms\data_out"
plot_dir = r"C:\Users\marie\rep_codes\udder_project\paper\plots"

df = pd.read_csv(features_path)

In [6]:
def list_columns(df, keyword):
    column_list = [col for col in df.columns if keyword in col]
    return column_list

def melt_frame(df, cols):
    selected_df = df[cols]
    # melted_df = pd.melt(df, id_vars=['cow', 'frame'], value_vars=cols)
    melted_df = pd.melt(df, id_vars=['cow'], value_vars=cols)
    return melted_df

def subset_df(df, keyword):
    kkword = '_' + keyword
    col = list_columns(df, keyword)
    melted_df = melt_frame(df, col)
    melted_df["variable"] = [val.replace(kkword, "") for val in melted_df["variable"]]
    return melted_df

# teat length

In [20]:
# mean and SD
keyword = "len"
sdf = subset_df(df, keyword)
sdf.groupby("variable").agg({"value":["mean", "std"]})

              value
               mean       std
variable
lb        35.675016  7.491108
lf        43.781803  6.899725
rb        35.881472  7.222288
rf        43.599371  7.588241

In [21]:
sdf["side"] = [s[-1] for s in sdf.variable]
sdf.groupby("side").agg({"value":["mean", "std"]})

          value
           mean       std
side
b     35.776537  7.345608
f     43.687847  7.247478

# teat distance

In [12]:
# mean and SD
keyword = "eu"
sdf = subset_df(df, keyword)
# melt 
sdf.groupby("variable").agg({"value":["mean", "std"]})

              value
               mean       std
variable
back       7.764703  2.487973
front     15.345102  3.199754
left      18.356451  4.197909
right     18.696804  3.712515

In [13]:
# mean and SD
keyword = "gd"
sdf = subset_df(df, keyword)
# melt 
sdf.groupby("variable").agg({"value":["mean", "std"]})

              value
               mean       std
variable
back      15.551711  3.142601
front     26.619918  3.663822
left      22.586132  3.914464
right     22.361380  3.002117

# udder volumne

In [14]:
# mean and SD
keyword = "vol"
sdf = subset_df(df, keyword)
# melt 
sdf.groupby("variable").agg({"value":["mean", "std"]})

             value
              mean       std
variable
lb        0.720089  0.243764
lf        2.940578  1.267339
rb        0.693389  0.220458
rf        2.788179  0.750434
udder     7.537096  1.790608

In [16]:
# mean and SD
keyword = "sarea"
sdf = subset_df(df, keyword)
# melt 
sdf.groupby("variable").agg({"value":["mean", "std"]})/100

              value
               mean       std
variable
lb         3.753671  1.262679
lf         7.049834  2.214843
rb         3.504454  1.105570
rf         7.148004  1.379156
udder     21.060382  3.039590